// Auto-generated offsets for assembly
// DO NOT EDIT - Generated by gen_offsets.c

#define task_struct_state 0
#define task_struct_pid 4
#define task_struct_name 8
#define task_struct_policy 40
#define task_struct_priority 44
#define task_struct_time_slice 48
#define task_struct_time_remaining 52
#define task_struct_stats 56
#define task_struct_context 88
#define task_struct_mm 140
#define task_struct_kernel_stack 144
#define task_struct_parent 148
#define task_struct_exit_code 152
#define task_struct_next 156
#define task_struct_prev 160

// cpu_context is at offset 88 within task_struct
#define cpu_context_eax 0
#define cpu_context_ebx 4
#define cpu_context_ecx 8
#define cpu_context_edx 12
#define cpu_context_esi 16
#define cpu_context_edi 20
#define cpu_context_ebp 24
#define cpu_context_esp 28
#define cpu_context_eip 32
#define cpu_context_eflags 36
#define cpu_context_cs 40

// Combined offsets (task_struct -> context -> field)
#define TASK_CONTEXT_ESP 116
#define TASK_MM 140

// address_space_t offsets
#define ADDRSPACE_PHYSICAL_ADDR 4

// Sanity checks
#define SIZEOF_TASK_STRUCT 164
#define SIZEOF_CPU_CONTEXT 52
