#include <stddef.h>
#include <stdio.h>
#include <kernel/process.h>
#include <kernel/paging.h>

#define OFFSET(structure, member) \
    printf("#define " #structure "_" #member " %zu\n", offsetof(struct structure, member))

#define DEFINE(name, value) \
    printf("#define " #name " %zu\n", (size_t)(value))

int main(void) {
    printf("# Auto-generated offsets for assembly\n");
    printf("# DO NOT EDIT - Generated by gen_offsets.c\n");
    printf("\n");

    // task_struct offsets
    OFFSET(task_struct, state);
    OFFSET(task_struct, pid);
    OFFSET(task_struct, name);
    OFFSET(task_struct, policy);
    OFFSET(task_struct, priority);
    OFFSET(task_struct, time_slice);
    OFFSET(task_struct, time_remaining);
    OFFSET(task_struct, stats);
    OFFSET(task_struct, context);
    OFFSET(task_struct, mm);
    OFFSET(task_struct, kernel_stack);
    OFFSET(task_struct, parent);
    OFFSET(task_struct, exit_code);
    OFFSET(task_struct, next);
    OFFSET(task_struct, prev);

    printf("\n");

    // cpu_context offsets (within task_struct)
    printf("# cpu_context is at offset %zu within task_struct\n",
           offsetof(struct task_struct, context));
    OFFSET(cpu_context, eax);
    OFFSET(cpu_context, ebx);
    OFFSET(cpu_context, ecx);
    OFFSET(cpu_context, edx);
    OFFSET(cpu_context, esi);
    OFFSET(cpu_context, edi);
    OFFSET(cpu_context, ebp);
    OFFSET(cpu_context, esp);
    OFFSET(cpu_context, eip);
    OFFSET(cpu_context, eflags);
    OFFSET(cpu_context, cs);

    printf("\n");

    // Combined offsets for convenience
    printf("# Combined offsets (task_struct -> context -> field)\n");
    printf("#define TASK_CONTEXT_ESP %zu\n",
           offsetof(struct task_struct, context) + offsetof(struct cpu_context, esp));
    printf("#define TASK_MM %zu\n", offsetof(struct task_struct, mm));

    printf("\n");

    // address_space_t offsets
    printf("# address_space_t offsets\n");
    printf("#define ADDRSPACE_PHYSICAL_ADDR %zu\n",
           offsetof(address_space_t, physical_addr));

    printf("\n");

    // Sanity checks
    printf("# Sanity checks\n");
    DEFINE(SIZEOF_TASK_STRUCT, sizeof(struct task_struct));
    DEFINE(SIZEOF_CPU_CONTEXT, sizeof(struct cpu_context));

    return 0;
}
